# admin/config.yml

backend:
  name: git-gateway
  branch: master # Asegúrate de que sea 'master' o 'main' según tu repositorio

publish_mode: editorial_workflow # Permite que el contenido subido necesite aprobación
media_folder: "Imagenes/uploads" # Carpeta donde Netlify CMS subirá las imágenes/archivos
public_folder: "/Imagenes/uploads" # URL base para acceder a esos archivos (ruta pública)

collections:
  # Colección de Libros
  - name: "libros" # Nombre interno para esta colección
    label: "Libros de la Biblioteca" # Etiqueta que verás en el CMS
    folder: "content/libros" # Dónde se guardarán los archivos de los libros (crearemos esta carpeta)
    create: true # Permite crear nuevos libros
    slug: "{{slug}}" # Define cómo se generan los nombres de archivo para los archivos de contenido (ej. 'titulo-del-libro.md')
    fields: # Campos que tendrá cada libro
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Portada del Libro", name: "cover_image", widget: "image", required: true, media_folder: "", public_folder: ""}
      - {label: "Archivo PDF del Libro", name: "pdf_file", widget: "file", required: true, media_folder: "", public_folder: ""}
      - {label: "Categorías", name: "categories", widget: "list", default: ["General"]}

  # Colección de Imágenes para el Collage
  - name: "collage" # Nombre interno de la colección
    label: "Imágenes del Collage" # Etiqueta que verás en el CMS
    folder: "content/collage" # Dónde se guardarán los archivos de las imágenes de collage
    create: true # Permite añadir nuevas imágenes
    slug: "{{slug}}" # Define cómo se generan los nombres de archivo
    fields: # Campos para cada imagen
      - {label: "Título/Descripción", name: "title", widget: "string", required: true}
      - {label: "Imagen", name: "image", widget: "image", required: true, media_folder: "", public_folder: ""}
      - {label: "Créditos (Opcional)", name: "credits", widget: "string"}